language: python
dist: focal
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
# command to install dependencies
install:
  - pip3 install .
  - pip3 install coverage coveralls
# command to run tests
script:
  - python3 -m ff3.ff3_test
  - coverage run --source ff3 --omit ff3/__main__.py,ff3/ff3_test.py,ff3/ff3_perf.py -m unittest ff3/ff3_test.py
after_success:
  - coveralls
